print("Hi, my name is RudeAI.")
print("I'd like to ask you a few questions.")
name = input("What is your name?")
print(name, "?!!! Why would anyone name a baby that?")
age = int(input("How old are you?"))
print("Oooooo!!!",age,"is getting up there")
hobby = input("What do you do for fun?")
print("I thought only nerds like to", hobby)
music = input("What kind of music do you like?")
print("Boooo!!! I wouldn't wish the sound of", music,"on my worst enemy.")
siblings = int(input("How many siblings do you have?"))
print(siblings,"? Wow, I hope the rest of your family is better looking.")
dream = input("What do you want to be when you grow up?")
print("I think you'd have to be smarter to be a",dream,".")
print("So",name,",you're",age,"...")
print("You like to",hobby,"and listen to",music,"...")
print("Good luck becoming a",dream,".")
print("I'm oly kiddin'",name,".")


