print("          A")
print("         AAA")
print("        AAAAA")
print("       AAAAAAA")
print("      AAA   AAA")
print("     AAA     AAA")
print("    AAAAAAAAAAAAA")
print("   AAAAAAAAAAAAAAA")
print("  AAA           AAA")
print(" AAA             AAA")
print("AAA               AAA")

print("    ^...^   ")
print("   / o,o \  ")
print("   |):::(|  ")
print("=====w=w=====")
